version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    hostname: zookeeper

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

    ports:
      - "2181:2181"

    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log

    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    hostname: kafka

    depends_on:
      - zookeeper

    ports:
      - "9092:9092"
      - "29092:29092"

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    volumes:
      - kafka_data:/var/lib/kafka/data

    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres

    environment:
      POSTGRES_DB: git_analytics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  producer:
    build:
      context: ./producer

    container_name: producer

    ports:
      - "5000:5000"

    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/git_analytics

    depends_on:
      - kafka

    restart: unless-stopped
  commit_consumer:
    build:
      context: .
      dockerfile: consumers/commit_consumer/Dockerfile

    container_name: commit_consumer

    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/git_analytics
      PYTHONPATH: /app
      PYTHONUNBUFFERED: "1"

    volumes:
      - .:/app

    depends_on:
      - kafka
      - postgres

    restart: unless-stopped
  
  pr_consumer:
    build:
      context: .
      dockerfile: consumers/pr_consumer/Dockerfile

    container_name: pr_consumer

    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/git_analytics
      PYTHONPATH: /app
      PYTHONUNBUFFERED: "1"

    volumes:
      - .:/app

    depends_on:
      - kafka
      - postgres

    restart: unless-stopped
  hotspot_consumer:
    build:
      context: .
      dockerfile: consumers/hotspot_consumer/Dockerfile

    container_name: hotspot_consumer

    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/git_analytics
      PYTHONPATH: /app
      PYTHONUNBUFFERED: "1"

    volumes:
      - .:/app

    depends_on:
      - kafka
      - postgres

    restart: unless-stopped
  ranking_consumer:
    build:
      context: .
      dockerfile: consumers/ranking_consumer/Dockerfile

    container_name: ranking_consumer

    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/git_analytics
      PYTHONPATH: /app
      PYTHONUNBUFFERED: "1"

    volumes:
      - .:/app

    depends_on:
      - kafka
      - postgres

    restart: unless-stopped
  
  analytics_api:
    build:
      context: .
      dockerfile: analytics/Dockerfile

    container_name: analytics_api

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/git_analytics
      PYTHONPATH: /app

    depends_on:
      - postgres

    restart: unless-stopped
  
  churn_consumer:
    build:
      context: .
      dockerfile: consumers/churn_consumer/Dockerfile

    container_name: churn_consumer

    depends_on:
      - kafka
      - postgres

    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/git_analytics
      PYTHONPATH: /app

    restart: unless-stopped
  
  superset:
    build:
      context: ./superset

    container_name: superset

    ports:
      - "8088:8088"

    environment:
      SUPERSET_SECRET_KEY: mysecretkey

    depends_on:
      - postgres

    restart: unless-stopped

    command: /init.sh

volumes:
  kafka_data:
  postgres_data:
  zookeeper_data:
  zookeeper_log: